version: '3.0'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metabase-database
    networks: 
      - metabase-net
    depends_on: 
      - metabase-database
  
  metabase-database:
    image: postgres:latest
    container_name: metabase-database
    hostname: metabase-database
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase
    networks: 
      - metabase-net

networks: 
  metabase-net:
    driver: bridge